language: python
python:
  - "2.7"
install:
  - sudo apt-get -qq install xvfb python-virtualenv chromium-browser
before_script:
  - ./setup_travis.sh
  - cd tests
script:  ./run_selenium_tests.sh
env:
  - BROWSER="Chrome"
  - BROWSER="Firefox"
